filetype off
syntax on
filetype plugin indent on     " required!
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'thaerkh/vim-indentguides'
call vundle#end() 

call plug#begin(expand('~/.vim/plugged'))
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'vim-scripts/vim-auto-save'
Plug 'tomtom/tcomment_vim'
Plug 'tpope/vim-surround'
Plug 'mattn/emmet-vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'dag/vim-fish'
Plug 'dart-lang/dart-vim-plugin'
Plug 'drewtempelmeyer/palenight.vim'
Plug 'arcticicestudio/nord-vim'
call plug#end()

"Plugins
map <C-n> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

function! Refresh()
    set noconfirm
    bufdo e!
    set confirm
endfunction
nmap <F5> :call Refresh()<CR>

let g:auto_save = 1 
let g:auto_save_silent = 1

map <silent> <F2> <ESC> :silent !chmod 755 %<CR> :!"%:p"<CR> :redraw!<CR>
set background=dark "clarear letra
colorscheme peachpuff
" set nolist "So pega se for essa linha de baixo descomentada (nao faz sentido)
" set cursorcolumn
set cursorline
set listchars=space:\ ,tab:>~ list
set showmatch "mostra pares de colchetes
set ruler " mostra a linha e coluna na statusbar
set number "exibe números nas linhas
set mouse=a "habilita todas as acoes do mouse
set guioptions=aAimrLT
set clipboard=unnamedplus
set encoding=utf-8
set nobackup
set wildmenu
set hlsearch
set incsearch
set autowrite
set smartindent "indentação de acordo com linguagem
set expandtab
set smarttab
set autoindent
set tabstop=2 shiftwidth=2 expandtab softtabstop=2
set conceallevel=0
let g:tex_conceal = ''

