#!/bin/bash
shopt -s expand_aliases
alias listfiles="find . -maxdepth 1 -type f,l -not -path '*/\.*' | sort"

if [[ $# -eq 1 ]] && [[ $1 =~ / || $1 =~ ^\.. ]] ;then
  sudo -E $EDITOR "$1"
 else
  file="$(listfiles | grep "$1" | sed -n "$([[ -n $2 ]] && echo $2 || echo 1 )"p ;)"
  if [ -z "$file" ]; then
    echo "File '$1' not fount"
  else
    sudo -E $EDITOR "$file" 2> /dev/null
  fi
fi

