#!/bin/bash
shopt -s expand_aliases
alias listfiles="find . -maxdepth 1 -type f,l -not -path '*/\.*' | sort"

if [[ $# -eq 1 ]] && [[ $1 =~ / || $1 =~ ^\.. ]] ;then
  sudo -E $EDITOR "$1"
 else
  file="$(listfiles | grep "$1" | sed -n "$([[ -n $2 ]] && echo $2 || echo 1 )"p ;)"
  if [ -z "$file" ]; then
    echo "File '$1' not fount"
  else
    echo "$(pwd)/$(basename $file)"
    echo -n "$(pwd)/$(basename $file)" | xsel -i -b
    # $HOME/.bin/mktouch "$HOME/.system/arch/$(pwd)/$(basename $file)"
  fi
fi



