#!/bin/bash

[[ "$PWD" == "$HOME" ]] && COMMAND=config || COMMAND=git
[[ "$COMMAND" == "$git" ]] && $COMMAND add .

$COMMAND commit -m "$([[ $# -eq 0 ]] && echo $(date +%F=%T) || echo $@)"
$COMMAND push