#!/bin/bash
shopt -s expand_aliases
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

if [[ "$PWD" == "$HOME" ]] ;then
  # -n to dry-run
  # dotfiles  add -vu .
  dotfiles  add -v .
  dotfiles commit -m "$([[ -z $@ ]] && echo $(date +%F=%T) || echo $@)"
  dotfiles push
else
  git add -v .
  git commit -m "$([[ -z $@ ]] && echo $(date +%F=%T) || echo $@)"
  # git push -u origin main
  git push
fi
