#!/bin/bash

print_help() { echo "usage: hd (o|c) (a|b|c) " ;}

hd="sd$([[ -n $2 ]] && echo "$2" || echo a)"
mnt="/mnt"


partitions_check() { 
  while [ ! "$(lsblk "/dev/$hd")" ] ;do sleep 0.5 ;done 
  echo "=> $hd found"  
}

luks_open() { 
  [[ ! -b /dev/mapper/$hd ]] &&  sudo cryptsetup -v open "/dev/$hd" "$hd" --key-file /boot/.keep &&  echo "=> Luks is open" 
}

luks_close(){ 
  [[ -b /dev/mapper/$hd ]] && sudo cryptsetup -v close "$hd" &&  echo "=> Luks is closed" 
}

partitions_mount(){
  [[ -b /dev/mapper/$hd ]]  && sudo mount -v "/dev/mapper/$hd" "$mnt" && echo "=> partition mounted"
}

partitions_umount(){
  grep -q "/dev/mapper/$hd" /proc/mounts && sudo umount -v "$mnt"
  while  grep -q "/dev/mapper/$hd" /proc/mounts ;do sleep 0.5 ;done
  echo "=> Partition umounted"
}


case $1 in
  o*)
  partitions_check || exit
  luks_open || exit
  partitions_mount || exit
  ;;
  c*)
  partitions_umount || exit
  luks_close || exit
  ;;
  *)
  print_help
  ;;
esac

